### ISSUE TITLE
useless radar

### ISSUE THREAD

**Issue by Pochtidruid** [AiYinZiLeGong/PUBG-Radar#65] opened 2018-02-22 15:55 UTC
![useless](https://user-images.githubusercontent.com/36651692/36548629-daf3766c-1801-11e8-9507-c92f350480e3.jpg)

in the last few laps people are not displayed at all on radar, or in last game 11 ppl alive but on radar just 4, how to fix it?
and when ppl, obviously, quickly enter the radar coverage area (1.5km) on transport at a speed of 100 km/h+ - they do not appear in it, i mean they are near to you, but not displayed on radar
use lic win10x64 laptop as middle pc and AiYinZiLeGong's fork with next adds:
https://github.com/PubgKnown/PUBG-Radar/commit/b610d1917f442ee13c150736ac45dc5147c87938
https://github.com/AiYinZiLeGong/PUBG-Radar/commit/32182dc838041124a0cffa60bd45cd3548615551
https://github.com/AiYinZiLeGong/PUBG-Radar/pull/21/files

**Comment by Pochtidruid** [comment] 2018-02-22 16:05
btw the forks of AiYinZiLeGong/Psycho7/TheUserUnknown - are compile without errors, run and work normally, fork of PubgKnown - compile without errors, but doest start, just nothing happens after starting up
where look for a solution?

**Comment by Sir3x** [comment] 2018-02-22 16:14
I am using @PubgKnown without any problem. 
Only this forks works for me due to i also has issue with own position. So, i just scroll map manually.

**Comment by Pochtidruid** [comment] 2018-02-22 16:26
@Sir3x so for u until the end of the game all the players are displayed normally?

**Comment by Sir3x** [comment] 2018-02-22 17:09
I just started to play with this radar. 
But yes, it's looks like no all players displayed at radar.

**Comment by al1m3rt** [comment] 2018-02-22 19:40
yeah i experianced some problems too, i had a game where last 5 players were alive airdrops. but i modified mine a lot so i cant keep track

**Comment by Psycho7** [comment] 2018-02-22 19:46
Emm did you guys talk about that yesterday's patch made radar useless? I didn't have time to play PUBG these days.

**Comment by Pochtidruid** [comment] 2018-02-22 19:53
@Psycho7 nope, this problem is during all week for me

**Comment by Psycho7** [comment] 2018-02-22 20:02
@Pochtidruid That's weird. Usually if radar works correctly before jumping, it just works until you leave.  Of course location of items are far from precise. FYI, I never use it on VM or another machine, which means I don't turn on Promiscuous Mode.

**Comment by Pochtidruid** [comment] 2018-02-22 20:07
@Psycho7 without VM or middle pc? then how? and yeap, radar works correctly before n after jumping, just for ur +-landing place

**Comment by Psycho7** [comment] 2018-02-22 20:13
Well I got 2 monitors connected to a single machine.

BTW, the location of yourself is fetched from RTP packets. And those packets may not be sent out when you are using the voice channel, which may be the reason.  See #10

**Comment by Pochtidruid** [comment] 2018-02-22 20:30
@Psycho7 emmm, so if i got 3 monitors connected to gaming pc, i can start radar without all those spoofings? just on another one from pubg monitor?

**Comment by PubgKnown** [comment] 2018-02-22 21:20
@Pochtidruid The one from my fork needs to be run from command line.

`java -jar .\target\pubg-radar-1.0-SNAPSHOT-jar-with-dependencies.jar GAME_PC_IP PortFilter`

**Comment by pornodog** [comment] 2018-02-23 12:38
@PubgKnown hey man how come when i run your fork, it gives me this error?

Exception in thread "main" java.lang.ExceptionInInitializerError
        at pubg.radar.GameKt.main(Game.kt:47)
Caused by: java.util.NoSuchElementException: Collection contains no element matching the predicate.
        at pubg.radar.sniffer.Sniffer.<clinit>(Sniffer.kt:206)
        ... 1 more

**Comment by Sir3x** [comment] 2018-02-23 13:11
@PubgKnown @Psycho7 @Pochtidruid - If your player location is work correct - can you please share pcap file or an example of UDP packet explanation ?

**Comment by oCortex** [comment] 2018-02-23 15:10
@pornodog I think you've entered your IP wrong. 

java -jar .\target\pubg-radar-1.0-SNAPSHOT-jar-with-dependencies.jar GAME_PC_IP PortFilter

**Comment by pornodog** [comment] 2018-02-23 15:46
I see my player though @oCortex  and everyone else. It's just the items I can't see

**Comment by Sir3x** [comment] 2018-02-23 16:07
@pornodog but @oCortex didn't create any PUBG fork.

**Comment by pornodog** [comment] 2018-02-23 16:17
@Sir3x i meant @PubgKnown

**Comment by Pochtidruid** [comment] 2018-02-23 17:22
how do I know in win which port is used to connect a middel pc to gaming?

**Comment by Psycho7** [comment] 2018-02-23 18:45
@Sir3x I want to but am not able to... I was trying to make my own radar however it's really really complex. This repo really save my life. XD

I can only tell you the position of yourself.  Look at your outgoing 86-byte udp packet. Check it's last 12 bytes, it should look like `00/ff xx xx xx 00/ff yy yy yy 00/ff zz zz zz`. And incoming 186-byte udp packets also have your position. Other than this, other information are divided into several bunches and distributed in different packets. After you capturing those, you need to parse them and place those bunches in right order and parse again, which is exactly why it's hard.

However, you can found a diagram about diagram on UC, though it's not that accurate. And of course you can also refer to this repo and the code of UE4.

**Comment by Psycho7** [comment] 2018-02-23 18:48
@pornodog It's weird, really. If you didn't modify any code, seeing player position means it's working as expected. Which repo are you using? This repo shall work as charm.

**Comment by Psycho7** [comment] 2018-02-23 18:53
@Pochtidruid If you want to use radar without middle machine or VM, use code before commit adb435ef8257dd1561bf6d781c96501151b25348. Build your packets and run, that's it. BTW, I never update from this repo since that commit LOL.

**Comment by Sir3x** [comment] 2018-02-23 19:03
@Psycho7 Thanks for this suggestion. I will try to find this packets. 
But, 86 byte - this total UDP packet size or only payload ?

**Comment by Psycho7** [comment] 2018-02-23 20:43
@Sir3x By 86 I mean the whole packet. It's 44 for the payload. [Here](https://github.com/AiYinZiLeGong/PUBG-Radar/blob/master/src/main/kotlin/pubg/radar/sniffer/Sniffer.kt#L225) is what this repo do.

**Comment by Sir3x** [comment] 2018-02-23 20:51
@Psycho7 But this is my issue. I see all traffic from my Game PC, but no any UDP packet with length 86.
May be because in-game VoiceChat totally  disabled in my country my UDP packet has different size.

**Comment by Pochtidruid** [comment] 2018-02-23 21:10
@oCortex @PubgKnown an interesting moment, when i run from command line:

java -jar .\target\pubg-radar-1.0-SNAPSHOT-jar-with-dependencies.jar GAME_PC_IP PortFilter MIDDLE_PC_IP

getting an error like @pornodog :
Exception in thread "main" java.lang.ExceptionInInitializerError
at pubg.radar.GameKt.main(Game.kt:47)
Caused by: java.util.NoSuchElementException: Collection contains no element matching the predicate.
at pubg.radar.sniffer.Sniffer.(Sniffer.kt:206)
... 1 more

but if changing IP places - everything starts working, i mean to:
java -jar .\target\pubg-radar-1.0-SNAPSHOT-jar-with-dependencies.jar MIDDLE_PC_IP PortFilter  GAME_PC_IP
without writing a middle pc ip - it does not work either

**Comment by Pochtidruid** [comment] 2018-02-24 01:19
![game](https://user-images.githubusercontent.com/36651692/36623827-84b0bff8-1919-11e8-947e-fd6db8a63600.jpg)

on the whole everything works perfectly as it should!
use last @PubgKnown fork on 2nd monitor, without spoofing

**Comment by Psycho7** [comment] 2018-02-24 02:54
@Pochtidruid IMHO, I don't think using another machine matters and it will bring out some unexpected problems. No one is going to scan all of your memory just for anti-cheating. The only company I know would do this is Tecent. Well, Tecent is PUBG's agent and operator in China now LOL.

**Comment by Psycho7** [comment] 2018-02-24 05:06
@Sir3x Unfortunately, you are right. Those packets are parts of in-game VoiceChat. In wireshark they are marked as RTP packets. I don't know why BlueHole did such a stupid thing... However, I heard about there are other ways to get your own position even more accurately, but not as easy as this.

So my suggestion is to find a way to enable your in-game chat. I don't understand why your country ban this... If my country want to ban something about PUBG, they will ban PUBG totally instead of only voice chat...

**Comment by Pochtidruid** [comment] 2018-02-24 05:59
performed a clean install win 10 on the gaming, JDK/JRE/Maven installed, @PubgKnown fork is compile without errors, but when i start .jar from cmd, i get:
![another one](https://user-images.githubusercontent.com/36651692/36626259-b30dc4be-1940-11e8-9b24-498b896c7e79.jpg)
is any idea what this library can be?

**Comment by Sir3x** [comment] 2018-02-24 06:33
@Psycho7 - i try to analyze whole game traffic and observe a lot of 6 bytes packets. And this packet looks like outgoing information from MyGamePCto GameServer. 
Now i will try to find a way how to decode this packets.

**Comment by Pochtidruid** [comment] 2018-02-25 09:25
@Sir3x в общих чертах, проблемы с отображением людей на карте - из-за неразборчивого режима работы сетевой, если запускать радар на том же пк, что и пубг, но 2-ом мониторе - радар работает отлично.

also @Psycho7 @PubgKnown how can I remove the showing on the radar of suppressors for pistols and smg?

**Comment by al1m3rt** [comment] 2018-02-25 15:17
java -jar tiled.jar (myip) PortFilter doesnt work for me. i got the same error as pornodog. my ip is correct. java file is at desktop same as the cmd file.

**Comment by Psycho7** [comment] 2018-02-25 19:56
@Pochtidruid See https://github.com/AiYinZiLeGong/PUBG-Radar/blob/master/src/main/kotlin/pubg/radar/ui/GLMap.kt#L415 & https://github.com/AiYinZiLeGong/PUBG-Radar/blob/master/src/main/kotlin/pubg/radar/ui/Style.kt & https://github.com/AiYinZiLeGong/PUBG-Radar/blob/master/src/main/kotlin/pubg/radar/struct/Item.kt

**Comment by Norxy** [comment] 2018-02-26 02:43
@al1m3rt 
Run in Command Prompt 'java -jar pubg-radar-1.0-SNAPSHOT-jar-with-dependencies.jar <middle_pc_ip> PortFilter <game_pc_ip>'

**Comment by al1m3rt** [comment] 2018-02-26 19:52
its a virtual machine, should i type the same ip adress twice?

**Comment by Pochtidruid** [comment] 2018-02-27 10:50
@PubgKnown use ur fork, all t2/t3 loot is displayed on the radar, except the 98kar, 
what could be the problem?

**Comment by al1m3rt** [comment] 2018-02-28 20:24
okay i got it working thanks

**Comment by linnnnnnnn** [comment] 2018-03-01 17:32
@Pochtidruid How do you do the display icon instead of a long string of letters？

**Closed** 2018-03-08 17:59 UTC
